apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
cloudWatch:
  clusterLogging: {}
kubernetesNetworkConfig:
  ipFamily: IPv4
managedNodeGroups:
  - amiFamily: AmazonLinux2
    desiredCapacity: 1
    disableIMDSv1: true
    disablePodIMDS: false
    iam:
      withAddonPolicies:
        albIngress: true
        appMesh: true
        appMeshPreview: true
        autoScaler: true
        awsLoadBalancerController: true
        certManager: true
        cloudWatch: true
        ebs: true
        efs: true
        externalDNS: true
        fsx: true
        imageBuilder: true
        xRay: true
    instanceSelector: {}
    labels:
      alpha.eksctl.io/cluster-name: my-cluster
      alpha.eksctl.io/nodegroup-name: ng-4371a5e7
    maxSize: 1
    minSize: 1
    name: ng-4371a5e7
    privateNetworking: false
    releaseVersion: ''
    securityGroups:
      withLocal: null
      withShared: null
    ssh:
      enableSsm: true
    tags:
      alpha.eksctl.io/nodegroup-name: ng-4371a5e7
      alpha.eksctl.io/nodegroup-type: managed
    volumeIOPS: 3000
    volumeSize: 20
    volumeThroughput: 125
    volumeType: gp3
metadata:
  name: my-cluster
  region: ap-northeast-2
  version: '1.27'
privateCluster:
  enabled: false
  skipEndpointCreation: false
vpc:
  autoAllocateIPv6: false
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: false
    publicAccess: true
  manageSharedNodeSecurityGroupRules: true
  nat:
    gateway: Single
