version: '3.7'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data

  web:
    image: leemhoon00/goorm-mission-1:v5
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: postgres
      DB_PORT: 5432
    ports:
      - 80:3000
    depends_on:
      - postgres

volumes:
  postgres:
