version: '3.7'
services:
  mysql:
    image: mysql:8.2.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - 3306:3306
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 1s
      timeout: 3s
      retries: 10
    volumes:
      - mysql:/var/lib/mysql
  web:
    image: leemhoon00/goorm-mission-2:v2
    container_name: web
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: test
      DB_PORT: 3306
    ports:
      - 80:3000
    depends_on:
      - mysql
volumes:
  mysql:
