apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: mysql
      containers:
        - name: mysql
          image: mysql:8.2.0
          envFrom:
            - configMapRef:
                name: mysql
          resources:
            limits:
              memory: '512Mi'
              cpu: '250m'
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql
              mountPath: /var/lib/mysql
