apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web
data:
  DB_HOST: mysql
  DB_USER: root
  DB_PASSWORD: root
  DB_DATABASE: test
  DB_PORT: '3306'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: leemhoon00/goorm-mission-2:v1
          resources:
            limits:
              memory: '256Mi'
              cpu: '500m'
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: web
